version: "3.8"

services:

  app:
    image: 975049893953.dkr.ecr.eu-north-1.amazonaws.com/nodeapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
